/*
 * The one description of both pages.
 *
 * Everything here is shared by tools/emit-pages.mjs. Editing this file and
 * re-running that generator is how the two layouts are changed; editing either
 * HTML file directly is undone by the next run.
 *
 * The two layouts
 *   classic  The original: a fixed 250px rail on the left, which becomes a
 *            sticky icon strip under 820px and a single bar under 560px. This is
 *            what shipped before the split and stays byte-identical in
 *            behaviour.
 *
 *   wide     A permanent top bar and a centred, width-capped content column.
 *            It never collapses the navigation into icons, so the labels stay
 *            legible and the targets stay large at every width, which suits a
 *            tablet, a desk or a head unit held further away than a phone.
 *
 * Why the markup is shared and only the CSS differs
 *   app/app.js looks up roughly 170 element ids unconditionally while wiring its
 *   event handlers, with no per-page guard, so a layout with its own markup
 *   would have to reproduce every one of them exactly. Sharing the DOM means the
 *   pages cannot disagree about behaviour, and a layout change stays a CSS
 *   change.
 */

/** Layouts, in the order the settings switcher lists them. */
export const LAYOUTS = [
  { name: "classic", file: "ev-tracker.html", label: "set.layoutClassic" },
  { name: "wide", file: "ev-tracker-wide.html", label: "set.layoutWide" },
];

/** The filename for a layout name, used by the switcher to build its href. */
export const fileFor = (name) => {
  const hit = LAYOUTS.find((l) => l.name === name);
  return hit ? hit.file : LAYOUTS[0].file;
};

/**
 * Stylesheet links, injected before </head>.
 *
 * app/app.css is the entire shared design system - tokens, a11y utilities and
 * every component. The layout sheet that follows it may only rearrange what
 * app.css defines: changing a component's colour or padding belongs in app.css,
 * because that is the part both pages share and neither may fork.
 */
/**
 * Stylesheet links, injected before </head>.
 *
 * Wrapped in sentinel comments so the generator can excise exactly its own
 * output on the next run. Filtering by pattern instead would miss the prose
 * above each link and the comments would accumulate, one pair per run.
 */
export const LINK_LINES = [
  "    <!-- stylesheets:begin (generated by tools/emit-pages.mjs, do not edit) -->",
  "    <!-- app/app.css is the shared design system: tokens, a11y utilities and",
  "         every component. Both layouts load it, so a component cannot diverge. -->",
  '    <link rel="stylesheet" href="app/app.css" />',
  "    <!-- The layout shell. May only rearrange what app/app.css defines. -->",
  '    <link rel="stylesheet" href="app/layout-__LAYOUT__.css" />',
  "    <!-- stylesheets:end -->",
];

/**
 * The script tail.
 *
 * Order is load-bearing and tools/test-wiring.mjs fails the build if an external
 * src moves after the application script. All three are classic scripts, not
 * modules: the app must also run from file://, where module scripts are blocked
 * by the CORS rules.
 */
export const SCRIPT_LINES = [
  "    <!-- scripts:begin (generated by tools/emit-pages.mjs, do not edit) -->",
  '    <script src="app/i18n.js"></script>',
  '    <script src="app/storage.js"></script>',
  '    <script src="app/app.js"></script>',
  "    <!-- scripts:end -->",
  "",
];